export { DefaultPage } from "./DefaultPage"
export { Register } from "./Register"
export { Login } from "./Login"
export { PasswordReset } from "./PasswordReset"
export { PasswordForgot } from "./PasswordForgot"
export { DashboardPage } from "./DashboardPage"
export { Profile } from "./Profile"
export { NotFound } from "./NotFound"
export { ContactUs } from "./ContactUs";